### ISSUE TITLE
压测与实际README的不符合

### ISSUE THREAD

**Issue by sky508** [Redick01/lightweight-rate-limiter#7]
你好，我这边使用你的原始代码进行压测时，发现不太符合，循环数2，线程200，使用的是sliding_window_rate_limiter算法，rate200，capacity200，被限流的次数低于50%

**Comment by Redick01** [comment]
> 你好，我这边使用你的原始代码进行压测时，发现不太符合，循环数2，线程200，使用的是sliding_window_rate_limiter算法，rate200，capacity200，被限流的次数低于50%

我说明一下，影响测试效果的情况有很多，比如：压力机性能，应用程序服务器性能，应用程序是否预热等，README中的压测结果是我多次执行出来的完美情况，你也可以多跑几次试一下，我这边程序经过一定流量预热后基本限流次数都会停留在50%

**Comment by sky508** [comment]
好的，谢谢大佬的解答



---- 回复的原邮件 ----
| 发件人 | redick ***@***.***> |
| 日期 | 2023年08月04日 17:36 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Redick01/lightweight-rate-limiter] 压测与实际README的不符合 (Issue #7) |

你好，我这边使用你的原始代码进行压测时，发现不太符合，循环数2，线程200，使用的是sliding_window_rate_limiter算法，rate200，capacity200，被限流的次数低于50%

我说明一下，影响测试效果的情况有很多，比如：压力机性能，应用程序服务器性能，应用程序是否预热等，README中的压测结果是我多次执行出来的完美情况，你也可以多跑几次试一下，我这边程序经过一定流量预热后基本限流次数都会停留在50%
