### ISSUE TITLE
redis数据生成问题

### ISSUE THREAD

**Issue by sky508** [Redick01/lightweight-rate-limiter#8]
如果在并发情况下，经过rateLimiterHandler.isAllowed这个逻辑的时候，如果有很多请求一次性上来，那执行lua脚本的时候不就会有问题

**Comment by sky508** [comment]
因为没有锁的话，请求都上来的话，参数capacity貌似没啥用把

**Comment by Redick01** [comment]
> 因为没有锁的话，请求都上来的话，参数capacity貌似没啥用把

并发的控制不是交给redis了吗？？？？
